import { ArrowUpRight, Check, CirclePlay, Flame, ListChecks, Plus, Target, Timer, TrendingUp } from 'lucide-react'
import type { AppState, Task } from '../types'
import { dateKeyFromTimestamp, formatDate, formatDuration, formatLongDate, percent, todayKey } from '../utils'
import { Badge, Button, Card, ProgressBar, SectionHeading } from './ui'
import { PageFrame, ScheduleTimeline, ScoreRing, StatCard, TaskRow } from './common'

interface DashboardProps { state: AppState; onNavigate: (page: 'tasks' | 'habits' | 'goals' | 'focus' | 'planner') => void; onToggleTask: (task: Task) => void }
const completionDate = (task: Task) => dateKeyFromTimestamp(task.completedAt)

export function Dashboard({ state, onNavigate, onToggleTask }: DashboardProps) {
  const today = todayKey()
  const hour = new Date().getHours()
  const greeting = hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening'
  const todayTasks = state.tasks.filter((task) => task.dueDate === today || completionDate(task) === today).sort((a, b) => (a.dueTime ?? '99:99').localeCompare(b.dueTime ?? '99:99'))
  const openTasks = todayTasks.filter((task) => task.status !== 'done')
  const completedTasks = todayTasks.filter((task) => task.status === 'done').length
  const todayHabits = state.habits.filter((habit) => habit.completedDates.includes(today)).length
  const focusMinutes = state.focusSessions.filter((session) => session.date === today).reduce((sum, session) => sum + session.duration, 0)
  const todayBlocks = state.plannerBlocks.filter((block) => block.date === today)
  const taskScore = percent(completedTasks, Math.max(todayTasks.length, 3))
  const habitScore = percent(todayHabits, Math.max(state.habits.length, 1))
  const focusScore = Math.min(100, Math.round((focusMinutes / 90) * 100))
  const scheduleScore = todayBlocks.length ? Math.round((todayBlocks.filter((block) => block.startTime < new Date().toTimeString().slice(0, 5)).length / todayBlocks.length) * 100) : 0
  const score = Math.round((taskScore + habitScore + focusScore + scheduleScore) / 4)
  const activeGoal = state.goals.find((goal) => goal.status === 'active')
  const goalProgress = activeGoal ? percent(activeGoal.milestones.filter((milestone) => milestone.completed).length, activeGoal.milestones.length) : 0

  return <PageFrame>
    <section className="signal-line grid gap-6 rounded-[24px] bg-ink p-6 text-paper shadow-lift sm:p-8 lg:grid-cols-[1fr_auto] lg:items-center lg:p-10"><div><div className="mb-5 flex flex-wrap items-center gap-2"><Badge tone="accent">{formatLongDate()}</Badge><span className="text-xs text-paper/55">Your day, in one place</span></div><h2 className="max-w-2xl font-display text-4xl leading-[1.04] tracking-tight sm:text-5xl">{greeting}, {state.profile.name || 'friend'}.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-paper/65">{openTasks.length ? `You have ${openTasks.length} open ${openTasks.length === 1 ? 'loop' : 'loops'} to move through.` : 'The day is open. Choose one useful next thing.'}{focusMinutes ? ` You’ve already made ${formatDuration(focusMinutes)} of room for focus.` : ''}</p><div className="mt-7 flex flex-wrap gap-3"><Button variant="secondary" onClick={() => onNavigate('focus')}><CirclePlay size={16} />Start a focus</Button><Button variant="ghost" className="text-paper/70 hover:bg-white/10 hover:text-paper" onClick={() => onNavigate('tasks')}><Plus size={16} />Add a task</Button></div></div><ScoreRing score={score} /></section>

    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Open today" value={`${openTasks.length}`} detail={`${completedTasks} completed`} icon={<ListChecks size={18} />} /><StatCard label="Focus time" value={formatDuration(focusMinutes)} detail={focusMinutes ? 'Nice momentum' : 'Start with 25 minutes'} icon={<Timer size={18} />} accent="bg-lavender/35" /><StatCard label="Habit rhythm" value={`${todayHabits}/${state.habits.length}`} detail="checked in today" icon={<Flame size={18} />} accent="bg-fern/25" /><StatCard label="Goal progress" value={`${goalProgress}%`} detail={activeGoal?.title ?? 'Create your first goal'} icon={<Target size={18} />} accent="bg-peach/45" /></div>

    <div className="grid gap-6 xl:grid-cols-[1.25fr_0.75fr]"><Card className="p-5 sm:p-6"><SectionHeading eyebrow="Next in line" title="Today’s tasks" description="Progress, not pressure." action={<Button variant="ghost" className="px-2" onClick={() => onNavigate('tasks')}>See all <ArrowUpRight size={15} /></Button>} />{todayTasks.length ? <div>{todayTasks.map((task) => <TaskRow key={task.id} task={task} onToggle={onToggleTask} onOpen={() => onNavigate('tasks')} />)}</div> : <div className="signal-line rounded-[12px] bg-canvas p-8 text-center"><p className="font-display text-xl tracking-tight text-ink">A clean slate.</p><p className="mt-1 text-sm text-muted">Add one small thing you’d be glad to finish.</p><Button className="mt-5" onClick={() => onNavigate('tasks')}><Plus size={16} />Add task</Button></div>}</Card><Card className="p-5 sm:p-6"><SectionHeading eyebrow="Capacity" title="Today’s rhythm" action={<Button variant="ghost" className="px-2" onClick={() => onNavigate('planner')}>Open planner <ArrowUpRight size={15} /></Button>} /><ScheduleTimeline blocks={todayBlocks} /><Button variant="secondary" className="mt-5 w-full" onClick={() => onNavigate('focus')}><CirclePlay size={15} />Protect a focus block</Button></Card></div>

    <div className="grid gap-6 lg:grid-cols-[0.9fr_1.1fr]"><Card className="p-5 sm:p-6"><SectionHeading eyebrow="Small returns" title="Habit check-in" action={<Button variant="ghost" className="px-2" onClick={() => onNavigate('habits')}>View habits <ArrowUpRight size={15} /></Button>} /><div className="space-y-2">{state.habits.slice(0, 4).map((habit) => { const complete = habit.completedDates.includes(today); return <button key={habit.id} onClick={() => onNavigate('habits')} className="flex min-h-14 w-full items-center gap-3 rounded-[12px] bg-canvas p-3 text-left transition hover:bg-citrus/20"><span className="flex h-9 w-9 items-center justify-center rounded-[10px] text-ink" style={{ backgroundColor: `${habit.color}35` }}>{habit.icon === 'moon' ? '◐' : habit.icon === 'sun' ? '☼' : habit.icon === 'footprints' ? '⌁' : '⌑'}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-ink">{habit.name}</span><span className="text-xs text-muted">{complete ? 'Checked in for today' : 'A small moment is enough'}</span></span><span className={`flex h-6 w-6 items-center justify-center rounded-full border ${complete ? 'border-moss bg-moss text-white' : 'border-ink/15 text-transparent'}`}><Check size={13} /></span></button> })}</div></Card><Card className="relative overflow-hidden bg-[#e7eef0] p-5 sm:p-6"><div className="relative"><SectionHeading eyebrow="Keep the long view close" title="A goal worth returning to" action={<Button variant="ghost" className="px-2" onClick={() => onNavigate('goals')}>All goals <ArrowUpRight size={15} /></Button>} />{activeGoal ? <div className="grid items-center gap-5 sm:grid-cols-[1fr_auto]"><div><Badge tone="success">{activeGoal.category}</Badge><h3 className="mt-3 font-display text-3xl tracking-tight text-ink">{activeGoal.title}</h3><p className="mt-2 max-w-lg text-sm leading-6 text-muted">{activeGoal.description}</p><div className="mt-5 flex items-center gap-3"><ProgressBar value={goalProgress} className="max-w-xs flex-1" /><span className="text-sm font-bold text-moss">{goalProgress}%</span></div><p className="mt-2 text-xs text-muted">{activeGoal.milestones.filter((milestone) => milestone.completed).length} of {activeGoal.milestones.length} milestones complete · target {formatDate(activeGoal.targetDate, { month: 'short', day: 'numeric' })}</p></div><div className="hidden h-24 w-24 items-center justify-center rounded-full border-8 border-moss/15 border-t-moss text-center sm:flex"><span className="font-display text-xl text-moss">{goalProgress}%</span></div></div> : <div className="py-5 text-sm text-muted">No active goal yet. Give your next season a shape.</div>}</div></Card></div>

    <div className="flex items-center gap-2 text-xs text-muted"><TrendingUp size={14} className="text-moss" />EiFlow learns from what you actually do. Your score is a signal, not a grade.</div>
  </PageFrame>
}
